#!/bin/bash
set -euo pipefail
IMAGE_NAME="$(XSAMTOOLS_HOME/docker_scripts/image_tag.sh)"
CONTAINER_NAME="${IMAGE_NAME}"
wid=$(docker ps -a --latest --filter "name=${CONTAINER_NAME}" --format="{{.ID}}")
if [[ -z $wid ]]; then
    docker pull ${IMAGE_NAME}
    wid=$(docker run \
          --mount type=bind,source=${XSAMTOOLS_HOME}/mount,target=/home/${XSAMTOOLS_DOCKER_USER}/mount \
          --name "${CONTAINER_NAME}" \
          -it -d \
          ${IMAGE_NAME})
    echo "Started new container ${wid}"
else
    echo "Logging into existing container ${wid}"
fi
docker start ${wid} || echo
docker exec -it $wid /bin/bash
